version: '2'

services:
    backend:
        build:
            context: .
        ports:
            - 5000:5000
            - 9229:9229 # debugger port
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        command: yarn rebuild:docker
        depends_on:
            - mongo
        environment:
            MONGO_URI: mongodb://mongo:27017/dev?authSource=admin&readPreference=primary&ssl=false

    mongo:
        image: mongo:4.0.5
        ports:
            - 27017:27017
            - 27018:27017
        volumes:
            - /usr/src/app/data/db
